# This is used for configurate server parameters

# 服务器信息配置
server_info :
  platform_id : 0
  server_id : 1

# 全局服务器信息
server_global:
  global_addr : "192.168.12.91"
  global_port : 8989
  global_access_key : "wearechampion"
  mysql_db_name : "global_db"
  mysql_addr : "127.0.0.1"
  mysql_port : 3306
  mysql_user : "root"
  mysql_passwd : "123456"

# 连接服务器配置
server_conn :
  client_listener : 6101
  max_client : 2000
  
# 游戏服务器配置
server_game :
  conn_listener : 6201
  is_gm_enable : false

# 登录服务器配置
server_login :
  conn_listener : 6301

# 战斗服务器配置
server_war :
  game_listener : 6401

# 聊天服务器配置
server_chat:
  listener : 6501

# 数据库配置
server_db :
  game_listener : 6901
  mysql_addr : "127.0.0.1"
  mysql_port : 3306
  mysql_user : "root"
  mysql_passwd : "123456"
  mysql_db_name : "game_db"

